import Foundation
import AppKit

class HTMLExporter {
    static func export(tutorial: Tutorial) -> URL? {
        // 🔥 修复点 1：安全解包 steps
        let steps = tutorial.steps ?? []
        
        // 1. 构建 HTML 头部
        var html = """
        <!DOCTYPE html>
        <html lang="zh-CN">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>\(tutorial.title) - Trace Guide</title>
            <style>
                body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; background: #f5f5f7; }
                .header { text-align: center; margin-bottom: 40px; }
                .title { font-size: 32px; font-weight: bold; color: #1d1d1f; }
                .meta { color: #86868b; margin-top: 10px; }
                .step-card { background: white; border-radius: 18px; padding: 24px; margin-bottom: 24px; box-shadow: 0 4px 12px rgba(0,0,0,0.05); transition: transform 0.2s; }
                .step-card:hover { transform: translateY(-2px); }
                .step-header { display: flex; align-items: center; margin-bottom: 16px; }
                .step-badge { background: #ff9500; color: white; font-weight: bold; padding: 4px 12px; border-radius: 20px; font-size: 14px; margin-right: 12px; }
                .app-tag { background: #e5e5ea; color: #1d1d1f; padding: 4px 10px; border-radius: 6px; font-size: 12px; font-weight: 600; }
                .instruction { font-size: 18px; font-weight: 500; color: #1d1d1f; margin-bottom: 16px; line-height: 1.4; }
                .screenshot-container { border-radius: 12px; overflow: hidden; border: 1px solid #e5e5ea; }
                img { width: 100%; display: block; }
                .footer { text-align: center; margin-top: 60px; color: #86868b; font-size: 14px; }
            </style>
        </head>
        <body>
            <div class="header">
                <div class="title">\(tutorial.title)</div>
                <div class="meta">Generated by Trace • \(steps.count) Steps</div>
            </div>
        """
        
        // 2. 循环添加步骤
        for (index, step) in steps.enumerated() {
            var imageHtml = ""
            if let imageData = step.imageData {
                let base64String = imageData.base64EncodedString()
                imageHtml = """
                <div class="screenshot-container">
                    <img src="data:image/png;base64,\(base64String)" alt="Step Screenshot">
                </div>
                """
            }
            
            let stepHtml = """
            <div class="step-card">
                <div class="step-header">
                    <span class="step-badge">STEP \(index + 1)</span>
                    <span class="app-tag">\(step.appName)</span>
                </div>
                <div class="instruction">\(step.instruction)</div>
                \(imageHtml)
            </div>
            """
            html += stepHtml
        }
        
        // 3. 闭合 HTML
        html += """
            <div class="footer">Created with Trace App</div>
        </body>
        </html>
        """
        
        // 4. 保存到临时文件
        do {
            let tempDir = FileManager.default.temporaryDirectory
            let fileName = "Trace_\(UUID().uuidString.prefix(6)).html"
            let fileURL = tempDir.appendingPathComponent(fileName)
            // 🔥 修复点 2：显式指定 String.Encoding.utf8
            try html.write(to: fileURL, atomically: true, encoding: String.Encoding.utf8)
            return fileURL
        } catch {
            print("Export failed: \(error)")
            return nil
        }
    }
}
